### ISSUE TITLE
v1.2.0 is broken

### ISSUE THREAD

**Issue by iyegoroff** [Blu-J/ts-pipe#420]
https://npmfs.com/package/ts-pipe/1.2.0/ - index.js and index.d.ts do not exist

**Comment by Blu-J** [comment]
Sorry, didn't check that I published correctly

![image](https://user-images.githubusercontent.com/2364004/89207107-7a6cda00-d577-11ea-8d24-4aea9ca80901.png)

Here's proof the latest patch for this version is correct
